[build.environment]
NODE_FLAGS = "--version"
NODE_VERSION = "16"

[build]
command = "npx pnpm@6 install --filter macro-playground --store-dir=node_modules/.pnpm-store && npx pnpm run build"
publish = "apps/website/dist"

# [[plugins]]
# package = "/.netlify/netlify-plugin-pnpm"
