[build.environment]
NODE_FLAGS = "--version"
NODE_VERSION = "16"

[build]
base = "apps/website"
command = "npx pnpm@6 i --store-dir=node_modules/.pnpm-store && npx pnpm build"
publish = "apps/website/dist"

# [[plugins]]
# package = "/.netlify/netlify-plugin-pnpm"
