[build.environment]
NODE_FLAGS = "--version"
NODE_VERSION = "16"

[build]
# base = "apps/website"
command = "npx pnpm@6 install --store-dir=node_modules/.pnpm-store && npx pnpm -F macro-playground && npx pnmp run build"
publish = "apps/website/dist"

# [[plugins]]
# package = "/.netlify/netlify-plugin-pnpm"
