[build.environment]
NODE_FLAGS = "--version"
NODE_VERSION = "16"

[build]
# base = "apps/website"
command = "npx pnpm -F macro-playground install && npx pnpm run build"
# publish = "apps/website/dist"

# [[plugins]]
# package = "/.netlify/netlify-plugin-pnpm"
