packages:
  - 'apps/**'
  - '!apps/macro-cli'
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/tests/**'

catalog:
  typescript: "^5.7.0"
  chevrotain: "^10.5.0"
  debug: "^4.3.7"

  # Testing
  vitest: "^2.1.5"
  "@vitest/expect": "^2.1.5"
  "@vitest/eslint-plugin": "^1.1.10"

  # Tooling
  tsx: "^4.19.2"
  vite: "^5.4.11"
  prettier: "^3.3.3"
  eslint: "^8.57.1"
  eslint-config-prettier: "^9.1.0"
  eslint-plugin-import: "^2.31.0"
  eslint-plugin-prettier: "^5.2.1"
  eslint-plugin-simple-import-sort: "^12.1.1"
  eslint-import-resolver-typescript: "^2.7.1"
  "@typescript-eslint/utils": "^8.14.0"
  "@typescript-eslint/parser": "^8.14.0"
  "@typescript-eslint/eslint-plugin": "^8.14.0"

  # Types
  "@types/node": "^22.9.0"
