name: Unit Tests

on:
  push:
    branches:
      - devel

jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Source
      - uses: pnpm/action-setup@v4
        name: Install PNPM
      - uses: actions/setup-node@v4
        name: Setup Node for PNPM
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - run: pnpm install
      - run: pnpm test
